### PR TITLE
"parse" improve proposal

### PR DESCRIPTION
**Pull request by denizzzka**
Proposal about #4 

How to use:
```D
        auto range = parseXML!dxmlConfig(res); // parseXML imported from dxml
        auto decodedStruct = range.parse.decodeXml!SomeStruct;
```

### CODE REVIEW

**Comment by FeepingCreature** [comment]
Looks nice, thank you! Could you throw in a small unittest for it?

**Comment by denizzzka** [comment]
done

**Comment by FeepingCreature** [comment]
Thanks! I'll take a look on Monday, since I'm on a short holiday now. (yay!) If I don't get back to you by Tuesday, I've lost the notification so please give me a ping by then. :)

**Comment by FeepingCreature** [comment]
Sorry for the late reply!

I meant, could you throw in a small unittest in `unittest/text/xml/DecodeTest.d` that actually uses this functionality with a `dxml` range? So it's nailed down and doesn't get removed during refactoring.

Looks good otherwise.

(Also, rebase on master please :) )

**Comment by denizzzka** [comment]
> (Also, rebase on master please :) )

Can you explain more?

**Comment by FeepingCreature** [comment]
`git checkout master; git pull; git checkout <branch>; git rebase master` will rewrite your commits to be as if they'd been added after the new master. Right now you're branching off a few commits back, because I've added commits to master after you opened your PR. Don't worry about it though, I can do it for you when merging.

**Comment by denizzzka** [comment]
It is a bad omen to use rebase :-)

**Comment by denizzzka** [comment]
> I meant, could you throw in a small unittest in unittest/text/xml/DecodeTest.d that actually uses this functionality with a dxml range? So it's nailed down and doesn't get removed during refactoring.

This can be checked by coverage analyzis

Sorry, I already removed serialized dependency from my srcs, so this PR isn't actual for me.

**Comment by FeepingCreature** [comment]
Fair nuf :) Thanks anyway.

**Pull request closed without merging**
